apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: flux-operator
      sourceRef:
        kind: HelmRepository
        name: controlplaneio